# Generated by Django 5.2.6 on 2025-09-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': '预约记录', 'verbose_name_plural': '预约记录'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='people_count',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='verification_code',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', '已确认'), ('completed', '已完成'), ('cancelled', '已取消')], default='confirmed', max_length=20, verbose_name='状态'),
        ),
    ]
