# Generated by Django 5.2.6 on 2025-09-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['start_time'], 'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, help_text='建议尺寸：800x600，支持 JPG/PNG', null=True, upload_to='activities/', verbose_name='活动封面图'),
        ),
    ]
