# Generated by Django 5.2.6 on 2025-09-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_options_activity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='勾选后，该活动将出现在小程序首页的「总活动列表」中', verbose_name='是否在总活动页展示'),
        ),
    ]
