# Generated by Django 5.2.6 on 2025-09-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', '客户'), ('staff', '员工'), ('boss', '管理者'), ('owner', '小程序所有者'), ('admin', '超级管理员')], default='customer', help_text='客户：普通用户；员工：店铺员工；管理者：店铺所有者；小程序所有者：系统管理员；超级管理员：开发者', max_length=20, verbose_name='用户角色'),
        ),
    ]
