# Generated by Django 5.2.6 on 2025-10-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', '客户'), ('merchant', '商家'), ('admin', '管理员')], default='customer', max_length=20, verbose_name='用户类型'),
        ),
    ]
