# Generated by Django 5.2.6 on 2025-10-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_role_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='积分'),
        ),
    ]
