# Generated by Django 5.2.6 on 2025-10-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
