# Generated by Django 5.2.6 on 2025-11-02 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_from',
            field=models.CharField(default='website', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_openid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_unionid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
        migrations.CreateModel(
            name='WechatAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=64)),
                ('unionid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('access_token', models.CharField(blank=True, max_length=512, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=512, null=True)),
                ('expires_in', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wechat_auths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wechat_auth',
            },
        ),
    ]
