# Generated by Django 5.2.6 on 2025-11-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_created_from_user_wechat_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_from',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wechat_info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wechat_unionid',
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat_openid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='微信OpenID'),
        ),
        migrations.DeleteModel(
            name='WechatAuth',
        ),
    ]
