# Generated by Django 5.2.6 on 2025-09-29 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('description', models.TextField(blank=True, verbose_name='店铺描述')),
                ('logo', models.ImageField(blank=True, upload_to='shop_logos/%Y/%m/%d/', verbose_name='店铺Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
                'ordering': ['-created_at'],
            },
        ),
    ]
