# Generated by Django 5.2.7 on 2025-10-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_points_price',
            field=models.IntegerField(blank=True, default=0, help_text='积分原价，用于显示折扣', null=True, verbose_name='积分原价'),
        ),
        migrations.AddField(
            model_name='product',
            name='points_price',
            field=models.IntegerField(default=0, help_text='购买此商品所需的积分数量，0表示不支持积分购买', verbose_name='积分价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='现金原价'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='现金价格'),
        ),
    ]
