# Generated by Django 5.2.6 on 2025-11-01 02:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='actual_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='total_points',
            field=models.IntegerField(default=0, verbose_name='积分总金额'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_points_price',
            field=models.IntegerField(default=0, verbose_name='商品积分价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='已支付'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='支付时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', '现金支付'), ('points', '积分支付')], max_length=10, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='现金总金额'),
        ),
        migrations.DeleteModel(
            name='OrderStatusLog',
        ),
    ]
